### ISSUE TITLE
birdfeeder.sh execution error

### ISSUE THREAD

**Issue by jcfontan** [google-coral/project-birdfeeder#10]
Unable to get the program to run consistently
Initial run after board startup results in the  uunending "Failed to Flush Wyaland connection" issue described earlier. Installing the getstreamer module or running in sudo does not resolve the issue. After ending in Ctrl Z, rerunning birdfeeder.sh results in the following:
Need assistance to troubleshoot.

Traceback (most recent call last):
  File "bird_classify.py", line 143, in <module>
    main()
  File "bird_classify.py", line 104, in main
    engine = ClassificationEngine(args.model)
  File "/usr/lib/python3/dist-packages/edgetpu/classification/engine.py", line 48, in __init__
    super().__init__(model_path)
  File "/usr/lib/python3/dist-packages/edgetpu/basic/basic_engine.py", line 92, in __init__
    self._engine = BasicEnginePythonWrapper.CreateFromFile(model_path)
RuntimeError: Error in device opening (/dev/apex_0)!

**Comment by jcfontan** [comment]
rebooted the board and reran and resulted in a different response with the  ending in a hung state...

 
Loading mobilenet_v2_1.0_224_quant_edgetpu.tflite with imagenet_labels.txt labels.
Detected EdgeTPU dev board.
Gstreamer pipeline:  v4l2src device=/dev/video0 ! video/x-raw,format=YUY2,width=640,height=480,framerate=30/1 ! queue max-size-buffers=1 leaky=downstream  ! tee name=t
            t. ! queue max-size-buffers=1 leaky=downstream ! glupload ! glfilterbin filter=glcolorscale
               ! video/x-raw,format=RGBA,width=320,height=180 ! videoconvert ! video/x-raw,format=RGB,width=320,height=180 ! appsink name=appsink sync=false emit-signals=true max-buffers=1 drop=true
            t. ! queue max-size-buffers=1 leaky=downstream ! glupload ! glfilterbin filter=glcolorscale
               ! rsvgoverlay name=overlay ! waylandsink
        
Warning: gst-resource-error-quark: Could not initialise Wayland output (7): gstwaylandsink.c(416): gst_wayland_sink_find_display (): /GstPipeline:pipeline0/GstWaylandSink:waylandsink0:
Failed to create GstWlDisplay: 'Failed to connect to the wayland display '(default)''

**Comment by hjonnala** [comment]
Please try with the latest code and feel free to reopen is issue still persists.
