### ISSUE TITLE
Failed to flush Wayland connection

### ISSUE THREAD

**Issue by pmankow** [google-coral/project-birdfeeder#11]
When running ./birdfeeder.sh --stream with Coral camera on the Dev Board, I get:

** (python3:4034): CRITICAL **: 20:24:43.409: Failed to flush Wayland connection

Hundreds of times. I have to ^Z to stop it.

As this is a bird feeder

**Comment by hjonnala** [comment]
the below error occurs if HDMI is not connected properly to Dev Board.

`** (python3:4034): CRITICAL **: 20:24:43.409: Failed to flush Wayland connection`
