### ISSUE TITLE
Using the USB accelerator rather than the board

### ISSUE THREAD

**Issue by mtsechan** [google-coral/project-birdfeeder#12]
Hello ,
If I have the USB accelerator rather than the board will the code know how to use it?
It runs but there is an if statement in gstreamer.py that chooses the 2nd option as the board is not found:
my question is regarding the performance difference between the 2 options particularly is the usb accelerator is being used at all?

if detectCoralDevBoard():
        SRC_CAPS = 'video/x-raw,format=YUY2,width={width},height={height},framerate=30/1'
        PIPELINE += """
            t. ! {leaky_q} ! glupload ! glfilterbin filter=glcolorscale
               ! {dl_caps} ! videoconvert ! {sink_caps} ! {sink_element}
            t. ! {leaky_q} ! glupload ! glfilterbin filter=glcolorscale
               ! rsvgoverlay name=overlay ! waylandsink
        """
    else:
        SRC_CAPS = 'video/x-raw,width={width},height={height},framerate=30/1'
        PIPELINE += """
            t. ! {leaky_q} ! videoconvert ! videoscale ! {sink_caps} ! {sink_element}
            t. ! {leaky_q} ! videoconvert
               ! rsvgoverlay name=overlay ! videoconvert ! ximagesink

**Comment by hjonnala** [comment]
@mtsechan 

Yes, it uses USB accelerator and performance in terms of speed would be lower compared to edgetpu as the Coral USB Accelerator is an accessory device that that adds the Edge TPU as a coprocessor to your existing system.
