### ISSUE TITLE
edgetpu python api deprecated

### ISSUE THREAD

**Issue by dcohen-hub** [google-coral/project-birdfeeder#13]
seems like birdfeeder.py needs to be re-written using PyCoral API

I'm a very beginning programmer but would appreciate any help?

getting the error
rom edgetpu.classification.engine import ClassificationEngine
ImportError: No module named 'edgetpu'

**Comment by hjonnala** [comment]
@dcohen-hub can you try solution provided in below reference:
https://github.com/robmarkcole/coral-pi-rest-server/issues/56#issuecomment-632125175

if it doesn't work try below coomands:
sudo apt-get update
sudo apt-get install python3-edgetpu
