### ISSUE TITLE
bird_classify.py won't run without a graphical display

### ISSUE THREAD

**Issue by johncblacker** [google-coral/project-birdfeeder#17]
I tried setting up my rpi4 board with pi camera in a window pointing to my birdfeeder for testing purposes.  I ssh into the rpi4 and issue the ./birdfeeder.sh command but gstreamer is producing an error indicating it cannot connect/open a display.  Why is this happening?  I don't see any requirements for a display on the board mounted in the birdfeeder.

**Comment by hjonnala** [comment]
Hello, yes, this project would need a HDMI monitor and we haven't tested this RPI4. Please check the gstreamer examples from [examples-camera](https://github.com/google-coral/examples-camera) repo for headless examples. Thanks!

**Comment by johncblacker** [comment]
Thanks!  I got around the problem in a “less elegant” way; so, I will implement your method as a permanent fix.

I appreciate the response.

 

jb
