### ISSUE TITLE
Mount Plate File 

### ISSUE THREAD

**Issue by awegmann** [google-coral/project-birdfeeder#4]
Hi.

The file 'mount_plate.stp' ist not a real CAD file, but a HTML file. Can you please exchange this with the correct file?

Regards
 Andreas

**Comment by FreddyLab** [comment]
I think the file can be found in the branch 'rename-mount-plate-file': https://github.com/google-coral/project-birdfeeder/blob/rename-mount-plate-file/Tree%20mount.STP

**Comment by ngrutas** [comment]
The CAD file was re-uploaded and will download properly now.
